[package]
name = "rclrs"
version = "0.2.0"
authors = ["Esteve Fernandez <esteve@apache.org>"]
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
libc = "0.2.43"
parking_lot = "0.11.2"

[dependencies.rosidl_runtime_rs]
version = "*"

[build-dependencies]
bindgen = "0.59.1"
